import {
  AppWindow,
  ChevronDown,
  ChevronRight,
  ArrowDownToLine,
  ArrowUpFromLine,
  Cpu,
  Gpu,
  Gauge,
  LayoutDashboard,
  MemoryStick,
  Monitor,
  Network,
  Globe,
  Settings,
  Thermometer,
  Info,
} from "lucide-react";
export const icons = {
  info: Info,
  app: AppWindow,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  overview: LayoutDashboard,
  hardware: Monitor,
  cpu: Cpu,
  gpu: Gpu,
  temperature: Thermometer,
  memory: MemoryStick,
  network: Network,
  ip: Globe,
  settings: Settings,
  gauge: Gauge,
  download: ArrowDownToLine,
  upload: ArrowUpFromLine,
  monitor: Monitor,
};
