[package]
name = "pinmeter-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pinmeter-core = { path = "../core" }
serde_json.workspace = true
tempfile = "=3.27.0"
reqwest = { version = "=0.13.5", default-features = false, features = ["rustls", "socks"] }
tokio = { version = "=1.53.1", features = ["time"] }
httpdate = "=1.0.3"

[target.'cfg(target_os = "windows")'.dependencies]
windows-numerics = "=0.3.1"
windows = { version = "=0.62.2", features = ["Win32_Graphics_Direct2D", "Win32_Graphics_Direct2D_Common", "Win32_Graphics_DirectWrite", "Win32_Graphics_Dxgi_Common", "Win32_Graphics_Gdi", "Win32_UI_Accessibility", "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_LibraryLoader", "Win32_System_Variant", "Win32_System_Ole", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Registry", "Win32_System_Com", "Win32_System_Diagnostics_Etw", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_Performance", "Win32_System_SystemInformation", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock", "Win32_Networking_WinHttp"] }

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
sysinfo = { version = "=0.39.6", default-features = false, features = ["system", "network"] }
